### PR TITLE
Handle illegal `engines` fields.

### LINKED ISSUE #388: Error when running installed binary
Running an `notion install`'ed binary resulting in odd manifest parsing error:

```
❯ RUST_BACKTRACE=1 NOTION_DEV=1 ember s -p 0
Notion error: Could not read package info for dependencies.

Please ensure that all dependencies have been installed.

cause: Could not parse project manifest
at /Users/rjackson/src/glimmerjs/glimmer-vm/node_modules/benchmark/package.json

Please ensure that the file is correctly formatted.

cause: Could not parse project manifest
at /Users/rjackson/src/glimmerjs/glimmer-vm/node_modules/benchmark/package.json

Please ensure that the file is correctly formatted.

cause: trailing characters at line 48 column 5

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::h2e0dcecdc2682f65 (0x10c5cf498)
   1: <failure::backtrace::Backtrace as core::default::Default>::default::h730ef2b795456565 (0x10c5cf754)
   2: <E as notion_fail::FailExt>::with_context::h9681ade47d178fd4 (0x10c233ca7)
   3: notion_core::manifest::Manifest::for_dir::h010d661f2d3f9d4b (0x10c2b8a85)
   4: notion_core::project::Project::dependent_binaries::hcd6d12a5bcc6b158 (0x10c2939f0)
   5: <lazycell::LazyCell<T>>::try_borrow_with::h40399a044c5b575b (0x10c2b2420)
   6: <notion_core::tool::binary::Binary as notion_core::tool::Tool>::new::h719245414131164f (0x10c254f01)
   7: notion_core::tool::execute_tool::he386e39c634b9d03 (0x10c256673)
   8: shim::main::h0cec617aa9ef3467 (0x10c210e3b)
   9: std::rt::lang_start::{{closure}}::hbb4fb3901c46bb08 (0x10c20f785)
  10: std::panicking::try::do_call::hbdc2ad4ee791d633 (0x10c5e81e7)
  11: ___rust_maybe_catch_panic (0x10c5f166e)
  12: std::rt::lang_start_internal::h3dc68cf5532522d7 (0x10c5e8cdc)
  13: _main (0x10c211058)
Error details written to: notion-error-2019-04-29_11_14_16.482.log
```

<details>
<summary>The error infers that `node_modules/benckmark/package.json` is invalid, but AFAICT it is not. See it here.</summary>

```json
{
  "name": "benchmark",
  "version": "1.0.0",
  "description": "A benchmarking library that works on nearly all JavaScript platforms, supports high-resolution timers, and returns statistically significant results.",
  "homepage": "http://benchmarkjs.com/",
  "main": "benchmark",
  "keywords": [
    "benchmark",
    "narwhal",
    "node",
    "performance",
    "ringo",
    "speed"
  ],
  "licenses": [
    {
      "type": "MIT",
      "url": "http://mths.be/mit"
    }
  ],
  "author": {
    "name": "Mathias Bynens",
    "email": "mathias@benchmarkjs.com",
    "web": "http://mathiasbynens.be/"
  },
  "maintainers": [
    {
      "name": "John-David Dalton",
      "email": "john.david.dalton@gmail.com",
      "web": "http://allyoucanleet.com/"
    },
    {
      "name": "Mathias Bynens",
      "email": "mathias@benchmarkjs.com",
      "web": "http://mathiasbynens.be/"
    }
  ],
  "bugs": {
    "email": "bugs@benchmarkjs.com",
    "url": "https://github.com/bestiejs/benchmark.js/issues"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/bestiejs/benchmark.js.git"
  },
  "engines": [
    "node",
    "rhino"
  ],
  "directories": {
    "doc": "./doc",
    "test": "./test"
  }
}
```

The error seems to be indicating that there are `Trailing characters at line 48, column 5`, which is exactly where the `"rhino"` string starts in the `engines` array.
</details>

Steps to reproduce:

```
# system setup
rm -rf ~/.notion && curl -sSLf https://get.notionjs.com | bash
notion install node latest
notion install yarn latest
notion install ember-cli latest

# project setup
git clone git@git.github.com:glimmerjs/glimmer-vm.git
cd glimmer-vm
yarn
ember s
```

---

I have a few specific questions here:

* Why is notion parsing `node_modules/benchmark/package.json` **at all**?
* The `node_modules/benchmark/package.json` in question is valid JSON AFAICT, why would it say that these are trailing characters?

### PR DESCRIPTION
**Pull request by chriskrycho**
- Fixes #388
- Adds a debugger launch config for VS Code, which I found useful (can drop it if people don't want it here)

### CODE REVIEW

File: crates/notion-core/src/manifest/serial.rs [hunk 1]
```diff
@@ -76,6 +81,31 @@ pub struct Engines {
...
+    /// all scenarios other than finding a valid POJO like `{ node: <spec> }`
+    /// because we are happy to use that information if it is available, but if
+    /// it is either unavailable or malformed, we simply fall back to our normal
+    /// handling.
+    pub fn deserialize<'de, D>(d: D) -> Result<Option<Engines>, D::Error>
+    where
+        D: Deserializer<'de>,
+    {
+        Deserialize::deserialize(d).map(|value: Option<Value>| match value {
+            Some(Value::Object(object)) => match object.get("node") {
```
Comment (charlespierce) [inline crates/notion-core/src/manifest/serial.rs]: We can probably simplify the flow of this block slightly using `if let`, since the fail case is the same in both matches:

```rust
Deserialize::deserialize(d).map(|value: Option<Value>| {
    if let Some(Value::Object(object)) = value {
        if let Some(Value::String(ref node)) = object.get("node") {
            return Some(Engines {
                node: node.to_string(),
            });
        }
    }
    None
})
```

I leave it up to you if you think that's better or not, it seems pretty close to me.

Comment (chriskrycho) [reply crates/notion-core/src/manifest/serial.rs]: Totally fair to raise – I went back and forth on this one myself. I ultimately went with the `match` statements for two (totally just personal preference) reasons:

1. It's both shorter (by two lines) and less deeply nested (by one level of indentation) to use the `match` expressions.
2. I lean toward expression evaluations, rather than control flow with early `return`s—for whatever reason they're just clearer to me.

Neither of those is particularly binding, but for those two reasons my inclination would be to leave it as is. If you or others find it clearer with the `if let's, I'm totally willing to change it!

Comment (charlespierce) [reply crates/notion-core/src/manifest/serial.rs]: Fair enough :+1:
